columnSuffix: null
contentColumnType: string
fieldGroup: 67150fa1-f4a5-4854-80ec-6b0c718aae53 # Blog Post Fields
handle: postCategories
instructions: ''
name: 'Post Categories'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:97aa735c-5210-4ab0-ba4f-7b34843da695' # Blog Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
