currLabel: Ресурсы
customIcon: null
enabled: true
handle: assets
icon: assets
layout: 595c95f9-5b81-40b6-abfa-42be5883fe6d # Default
newWindow: false
order: 3
prevLabel: Ресурсы
prevUrl: assets
type: ''
url: assets
